### PR TITLE
feat: send amiibo report

### PR DESCRIPTION
**Pull request by spacemeowx2**
Closes: #27 

change requests are welcome

### CODE REVIEW

**Comment by mart1nro** [comment]
Thank you really much for this cool feature.

I'm currently moving and don't have access to a game that supports amiibo at the moment. It will take me some time to fully look into this.

So far I checked that the Switch is able to recognize an amiibo in the settings menu. This looks really promising. Can't wait to fully test this.

**Comment by mart1nro** [comment]
@spacemeowx2 Currently looking through the code. What does mcu stand for?

**Comment by spacemeowx2** [comment]
I guess mcu includes IR and NFC. https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/66935b7f456f6724464a53781035d25a215d7caa/bluetooth_hid_subcommands_notes.md#subcommand-0x21-set-nfcir-mcu-configuration

**Comment by colemickens** [comment]
I was able to validate this as working. Thanks for this @spacemeowx2!

Using a Raspberry Pi 4 running Raspbian and this PR with `joycontrol`, I was able to send `BOKOBLIN.bin` to my Switch with just a bluetooth dongle.

**Comment by benhid** [comment]
Tested using Raspberry Pi Zero W with Raspbian Lite (2020-02-13). Thank you @spacemeowx2!

PS. `libhidapi-hidraw0` is required

**Comment by 0mie** [comment]
> I was able to validate this as working. Thanks for this @spacemeowx2!
> 
> Using a Raspberry Pi 4 running Raspbian and this PR with `joycontrol`, I was able to send `BOKOBLIN.bin` to my Switch with just a bluetooth dongle.

How'd you install it on Raspbian?

**Comment by colemickens** [comment]
I wrote this up for Ubuntu-in-a-VM-on-Windows users, but it should basically be the same thing for Raspbian: https://gist.github.com/colemickens/b08d1a339f4483c6b3c08e739d6cf5d0.

**Comment by mart1nro** [comment]
@spacemeowx2 
> I guess mcu includes IR and NFC.

I'm guessing MCU stands microcontroller unit, meaning we are sending commands to the microcontroller which handles ir and nfc. I refactored the code a bit and renamed the things according to that.

It would be nice if you could add some more comments in the mcu code, to explain the meaning of bits and byte strings you are setting. I would also like to dig into that a bit, to be able to maintain the code in the future. Which resource did you use to implement nfc?

Anyways, since the code works and most of it not being API relevant, I'll merge this now. Thanks again for implementing NFC.

**Comment by ydxred** [comment]
Can't connect!!!!

**Comment by leoleoasd** [comment]
>  Can't connect!!!!

**you are supposed to create a issue rather than asking here**. Please also provide the error info. It seems that you are using Chinese ubuntu, and the Bluetooth program is not happy with utf-8.
----
**你应该创建一个issue, 而不是回复这个pr**. 你也应该提供错误提示框中的完整信息, 看上去是因为你使用了中文的ubuntu, 而bluetooth程序在处理utf8编码的时候有问题.

**Pull request merged**
