### PR TITLE
[WIP]: Amiibo writing

### PR DESCRIPTION
**Pull request by Poohl**
I figured the basics of the switch writing to amiibos out. It isn't enough to just write like with the regular controllers, however it works in that it creates valid registered amiibos. It does so by executing all he write requests by the switch and then reverting some to remove the 'currently writing to tag' message.

This Pull is on top of #89 and as I said, it only works because I can recover failed amiibo writes, not because the write succeds so some parts are still very hacky.

This is only tested for registering users currently, I'll test splatoon gear save soon. Anyhow, the current way of doing things is as follows:
- start joycontrol and set nfc
- go to system settings->amiibo->regiter user
- It'll read whatever is in your dump
- continue and enter Mii & name
- click ok
- It'll try to write and you should see 15 'write amiibo' log messages, then 'created backup' and a 'saving amiibo' messages.
- the switch will state that writing failed and prompt you to try again, don't do that
- instead press home to get out of that screen.
- Now the amiibo is registered as you entered.

### CODE REVIEW

**Comment by Poohl** [comment]
After a few prayers I was gifted with a more successful write while proxieing and got a bit more info on what should happen after the write is through, I updated https://gist.github.com/Poohl/e0f254b3e02051b18c7e9f4f032883be again.

**Comment by mehak** [comment]
Following your procedure (with minor modification) I was able to write-back with Super Smash Bros. Ultimate.

1. start joycontrol and set nfc
2. go to system settings->amiibo->regiter user
3. It'll read whatever is in your dump
4. continue and enter Mii & name
5. click ok
6. It'll try to write and you should see 15 'write amiibo' log messages, then 'created backup' and a 'saving amiibo' messages.
7. the switch will state that writing failed and prompt you to try again, don't do that
8. instead press home to get out of that screen.
9. Press "x" and follow prompts to close Super Smash Bros. Ultimate
10. Re-open and go back to the amiibo menu to confirm you can read it back after registering.
11. Now the amiibo is registered as you entered.

**Edit**: After loading the amiibo fighter and then saving again, I was unable to re-read it. I will try to troubleshoot more later today or this week.

**Comment by Poohl** [comment]
Update: I figured out a way to get around the "press home" on the error message: by briefly reporting another Tag it immediately exits this screen. I assume this is some kind of panic-behaviour by the switch but it works well. (That's the new commit 2bf640e)

and as @mehak reported writing other stuff to the amiibo failes for some reason. I'm testing on Splatoon's "save outfit" thing as I don't have SSBU. Kinda odd, since as far a I can tell it just rewrites the entire amiibo every time, but I'll look into that.

Also: If anyone knows other places where the "Please remove amiibo" prompt appears, please tell me I'd like to capture the "correct" way to get out of there.

**Comment by Lucaiii** [comment]
hehe longmiibo

**Comment by Poohl** [comment]
Will create a new pull request to reflect the new changes and include all the additions. Will update the comment to include a link. 

It's pull request #110

**Pull request closed without merging**
